language: java
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE c4sg;'
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('mysql') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app:
    master: c4sg-dev
    staging: c4sg-staging
    prod: c4sg-prod
