--load data in the column `display_order`
UPDATE `c4sg`.`user_skill` SET `display_order`='1' WHERE `id`='1';
UPDATE `c4sg`.`user_skill` SET `display_order`='2' WHERE `id`='2';
UPDATE `c4sg`.`user_skill` SET `display_order`='3' WHERE `id`='3';
UPDATE `c4sg`.`user_skill` SET `display_order`='4' WHERE `id`='4';
UPDATE `c4sg`.`user_skill` SET `display_order`='5' WHERE `id`='5';
UPDATE `c4sg`.`user_skill` SET `display_order`='6' WHERE `id`='6';
UPDATE `c4sg`.`user_skill` SET `display_order`='1' WHERE `id`='7';
UPDATE `c4sg`.`user_skill` SET `display_order`='2' WHERE `id`='8';
UPDATE `c4sg`.`user_skill` SET `display_order`='3' WHERE `id`='9';
UPDATE `c4sg`.`user_skill` SET `display_order`='4' WHERE `id`='10';
UPDATE `c4sg`.`user_skill` SET `display_order`='5' WHERE `id`='11';
UPDATE `c4sg`.`user_skill` SET `display_order`='6' WHERE `id`='12';
UPDATE `c4sg`.`user_skill` SET `display_order`='1' WHERE `id`='13';
UPDATE `c4sg`.`user_skill` SET `display_order`='2' WHERE `id`='14';
UPDATE `c4sg`.`user_skill` SET `display_order`='3' WHERE `id`='15';
UPDATE `c4sg`.`user_skill` SET `display_order`='4' WHERE `id`='16';
UPDATE `c4sg`.`user_skill` SET `display_order`='5' WHERE `id`='17';
UPDATE `c4sg`.`user_skill` SET `display_order`='6' WHERE `id`='18';
